version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile_app
    command: sbt run
    volumes:
      - .:/app
      - ./.ivy2:/root/.ivy2
      - ./.sbt:/root/.sbt
      - ./.cache:/root/.cache
    working_dir: /app
    tty: true
    ports:
      - "9000:9000"
